deploy:
  provider: npm
  email: r.rijnberk@gmail.com
  api_key:
    secure: iTaWw8g92BTcRH63g1F9ZWI1MKRqXJ2KkOhiddJCKiSUlkU6VknKtQ863ojMN1W1vjhnKqRx/z5aDApXWibTdjIQiJ5yqTqMhCQS2ikYWKeEkG5Qi5IRvOsWQdNsdl8bWOVqK4gul8h+1TgRiVBsg8RR1eHnh3tg2u/ILyKbbCA2iTk2jlOfVDPhIor9E2XbWTq8fLV80C8Y7V/C2vbdD0DcrdvnG8LfrTGsCsyyFhxB4+z04qDUxWbLyiOrlSRzYNl/131rUtAvRmxXjKN4QEa2lztV3AbcSs93efFRm3boQJWcn7GOYoqRPBrxWkyUtuRI8+WW2Iv4REb3bhHljcJhDOwAU8ezTtLH1ypX2DLPyVBLJWz6FVtmJn7bBg0IROFMuOKom8vZiCohy3vFm5Cq6w5OaXhKm61pZo2vtiw4L4PxYX/5ytxnCv4fzqJUGxRPj/JgLlnh93XoNxiRBRI/L4nTIUEUMl8HXF9qtR2f8+swEKBCLgyiwpUvU3ntjsTuHgJZxVozg1qtbUFJCW9BHkNMglgLOdd8xWK92L2xG3cYOgNKQTQU6M2UHqNQqz/1DglpuaygOludFv/HSGrdGafI1Pkv9kziz3iWAA/NRQMYSmid0B1rbqI4lwgwxBdRR31oXgs2bkvSv360TiN2tXn5+FH5/1h/R3jdt4E=
  on:
    repo: rrijnberk/sass-theme-generator
    branch: master
